[package]
name = "orangutan-rl"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.21.0", features = ["wgpu", "train", "vision", "ndarray"] }
itertools = "0.14.0"
plotters = "0.3.7"
rand = "0.10.1"
ringbuffer = "0.16.0"
gorilla-physics = { path = "../gorilla-physics/"}
nalgebra = { version = "0.33"}

[lib]
name = "orangutan_rl"
path = "src/lib.rs"
crate-type=["cdylib", "rlib"]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "demo"
path = "src/demo.rs"


[[bin]]
name = "policy_gradient"
path = "src/policy_gradient.rs"


[[bin]]
name = "vpg"
path = "src/vpg.rs"


[[bin]]
name = "vpg_continuous"
path = "src/vpg_continuous.rs"

[[bin]]
name = "vpg_pendulum"
path = "src/vpg_pendulum.rs"
