[package]
name = "orangutan-rl"
version = "0.1.0"
edition = "2024"

[dependencies]
burn = { version = "0.21.0", features = ["wgpu", "train", "vision"] }

[lib]
name = "orangutan_rl"
path = "src/lib.rs"
crate-type=["cdylib", "rlib"]

[[bin]]
name = "main"
path = "src/main.rs"

[[bin]]
name = "test"
path = "src/test.rs"

[[bin]]
name = "demo"
path = "src/demo.rs"
